group: edge
dist: trusty
language: java
language: node_js
node_js:
  # lts
  - 6
  # latest
  - 7
jdk: oraclejdk8
install: true
env:
  SPRING_PROFILES_ACTIVE: default
  DOCKER_COMPOSE_VERSION: 1.9.0
before_install:
  ## node
  #- nvm install 7
  # chrome
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  # gradle
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk selfupdate
  - touch "$HOME/.sdkman/etc/config"
  - sed -i -e 's/^sdkman_auto_answer=false$/sdkman_auto_answer=true/g' "$HOME/.sdkman/etc/config"
  #- sdk use gradle < /dev/null
  #- sdk install gradle < /dev/null
  - sdk use gradle
  - sdk install gradle
  - mkdir -p "$HOME/.sdkman/etc"
  - sdk use gradle
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  # docker
  - sudo rm /usr/local/bin/docker-compose
  - export DOCKER_COPOSE_URL=https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m`
  - echo using\ $DOCKER_COPOSE_URL
  - curl -L $DOCKER_COPOSE_URL > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
script:
  - gradle --parallel ui build -x test
  - gradle --parallel ci test
after_script:
  - killall -9 node
  - gradle --stop
cache.directories:
  - ui/node_modules/
  - $HOME/.gradle/
  - $HOME/.m2/
