# # http://localhost:15672
rabbitmq:
   image: rabbitmq:3-management
   container_name: rabbitmq-admin
   environment:
     RABBITMQ_DEFAULT_USER: admin
     RABBITMQ_DEFAULT_PASS: admin
   ports:
     - "5672:5672"
     - "15672:15672"
     - "25672:25672"

mongo-express:
  container_name: mongo-express
  image: mongo-express
  environment:
    ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
    ME_CONFIG_SITE_BASEURL: /
  ports:
    - "8081:8081"
  links:
    - mongo

mongo:
  container_name: mongo
  image: mongo
  environment:
    - MONGO_PORT_27017_TCP_ADDR=localhost
    - MONGO_PORT_27017_TCP_PORT=27017
  ports:
    - "27017:27017"
