server.port: 0
spring:
  application.name: consumer
  cloud.stream.bindings.userInputChannel:
    destination: user
    # use group option for writing with fallback
    group: durable-user
  rabbitmq:
    username: admin
    password: admin
    listener:
      acknowledge-mode:
