server.port: 0
spring:
  application.name: consumer
  cloud.stream.bindings.input:
    destination: user
    # use this option for writing with fallback
    group: user-consumer
  rabbitmq:
    username: admin
    password: admin
    listener:
      acknowledge-mode:
