users:
  credentials:
    admin:
      username: admin1
      password: admin1
      role: CONFIG_ADMIN
    user1:
      username: user1
      password: user1
      role: CONFIG_USER
    user2:
      username: user2
      password: user2
      role: CONFIG_USER
