spring:
  profiles.include: 'server,users-credentials,mustache'
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      EAGER_SERIALIZER_FETCH: true
      INDENT_OUTPUT: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      FAIL_ON_IGNORED_PROPERTIES: false
