users:
  credentials:
    admin:
      username: admin
      password: admin
      role: ADMIN
    user1:
      username: user1
      password: user1
      role: USER
    user2:
      username: user2
      password: user2
      role: USER
