server.port: 0
spring:
  application.name: producer
  cloud.stream.bindings.userOutputChannel:
    destination: user
    # use group option for writing with fallback
    group: durable-user
  rabbitmq:
    username: admin
    password: admin
fixedDelay: 500000
